site_name: p_cards
site_url: https://p-nutyx.github.io/p_cards//
site_description: Package Management Utilities for NuTyX-Linux (development repo of peter1000)
site_author: peter1000
#site_favicon: images/p_cards_favicon.ico

repo_url: https://github.com/P-NuTyX/p_cards//

pages:
- Home: 'index.md'

- About:
    - Readme: about/readme.md
    - License: about/license.md
    - Changelog: about/changelog.md

use_directory_urls: true
copyright: Copyright (c) 2016, <strong>peter1000</strong> <a href="https://github.com/peter1000">https://github.com/peter1000</a> plus contributors.

theme: 'bootstrap'
